@host = http://localhost
@port = 5272
@HostAddress = {{host}}:{{port}}

GET {{HostAddress}}/api/tasks

###

GET {{HostAddress}}/api/tasks/1

###

POST {{HostAddress}}/api/tasks
Content-Type: application/json

{
  "Title": "New Task",
  "Description": "New Task Description"
}

###


PATCH {{HostAddress}}/api/tasks/1
Content-Type: application/json

{
  "Title": "Updated Task",
  "Description": "Updated Task Description",
  "SubTaskIds": [6]
}

###

DELETE {{HostAddress}}/api/tasks/4

###

DELETE {{HostAddress}}/api/tasks/1/subtasks
Content-Type: application/json

{
  "SubTaskIds": [4, 3]
}

###

POST {{HostAddress}}/api/tasks/1/subtasks
Content-Type: application/json

{
  "SubTaskIds": [2]
}
